const slides = [
  {
    title: "Apresentação",
    subtitle: "",
    postedAt: " ",
    link: "https://docs.google.com/presentation/d/1zEOAOtmdudtlx4nJC4rcLvXjSsabMcGt3whVJA5omD4/edit#slide=id.g2121d33469a_0_27",
  },
  {
    title: "02_PEOO",
    subtitle: "Estrutura Condicional - IF ELSE",
    postedAt: " ",
    link: "https://docs.google.com/presentation/d/1rVbGcnqnlzeFMuJdBuHJgiZ6xoHOT02SG_7uxAOD4Ic/edit#slide=id.p1",
  },
  {
    title: "03_PEOO - Estruturas de Repetição",
    subtitle: "Estrutura de Repetição - WHILE",
    postedAt: " ",
    link: "https://docs.google.com/presentation/d/1FTQb9XB2cnTCuwrmexpxd4_XXIwp2dEgvORZG_bhVZU/edit#slide=id.p1",
  },
  {
    title: "04_PEOO - Listas",
    subtitle: "Visão Geral",
    postedAt: " ",
    link: "https://docs.google.com/presentation/d/1Z1UlOwiHb9pgESZuZxnLGMQiprzVqubEvEYIbUI8y_M/edit#slide=id.p1",
  },
  {
    title: "05_PEOO - Estruturas de Repetição",
    subtitle: "Estrutura de Repetição - FOR",
    postedAt: " ",
    link: "https://docs.google.com/presentation/d/1IeOoD0tmlqNi9DU59izOsY_gSh42LfezD-EcroHxnaY/edit#slide=id.p1",
  },
  {
    title: "06_PEOO - Strings e Listas",
    subtitle: "Introdução",
    postedAt: " ",
    link: "https://docs.google.com/presentation/d/1fnMLPRBsf9PPp0xIb3_txlTi0zCeO5EvCxvDM3IHNYo/edit#slide=id.p1",
  },
  {
    title: "07_PEOO - Listas de Listas",
    subtitle: "Matrizes",
    postedAt: " ",
    link: "https://docs.google.com/presentation/d/1ZuQoNSgPMSzH3EP_UgZCoJFy7SZNgnyYZE30Ig1nbCQ/edit#slide=id.p1",
  },
  {
    title: "08_PEOO - Registros",
    subtitle: "Registros",
    postedAt: " ",
    link: "https://docs.google.com/presentation/d/1aQu9lwoWPLu7dG1UBjyGUaGb554IWI-PpLAcCNQ-lOU/edit#slide=id.p1",
  },
  {
    title: "09_PEOO - Arquivos",
    subtitle: "Trabalhando com arquivos em Python",
    postedAt: " ",
    link: "https://docs.google.com/presentation/d/1p6CXiFq8mioJw4DWljtTwFrin9b-xmaWpsN5pGwn0co/edit#slide=id.p1",
  },
  {
    title: "10_PEOO - Funções",
    subtitle: "Trabalhando com funções em Python",
    postedAt: " ",
    link: "https://docs.google.com/presentation/d/1HMnbqZPotyFgl_d1b6fY_aEYIh9FST5Hyj-I6UZimEM/edit#slide=id.p1",
  },
  {
    title: "11_PEOO - Bibliotecas",
    subtitle: "Trabalhando com bibliotecas em Python",
    postedAt: " ",
    link: "https://docs.google.com/presentation/d/1P76aggy563mGvjknr1str_Hv3AOX7ukZ0IuopxHeTFc/edit#slide=id.p1",
  },
  {
    title: "12_PEOO - POO - 1",
    subtitle: "Classes e Objetos",
    // postedAt: "19/07/2023",
    postedAt: " ",
    link: "https://docs.google.com/presentation/d/1VaEKpswz_6umZZaMIsejgNLQQDq1MxNzEemyc-FUIoc/edit#slide=id.p1",
  },
  {
    title: "13_PEOO - POO - 2",
    subtitle: "Encapsulamento, Herança e Polimorfismo",
    // postedAt: "26/07/2023",
    postedAt: " ",
    link: "https://docs.google.com/presentation/d/1xZvxAhHHKHGdCr7SSu80IyUStkiY_181_DbRbriMSio/edit#slide=id.p1",
  },
  {
    title: "14_PEOO - POO - Atv. - 1",
    subtitle: "Exercício de Fixação",
    // postedAt: "26/07/2023",
    postedAt: " ",
    link: "https://docs.google.com/presentation/d/12ZtLR3--1oDxWWeJr8xMJa9VrPeuVaZV46N_JDyA_fU/edit#slide=id.g1e42f8f1aa6_0_0",
  },
  {
    title: "15_PEOO - POO - 3",
    subtitle: "Relacionamento entre Classes",
    // postedAt: "28/07/2023",
    postedAt: " ",
    link: "https://docs.google.com/presentation/d/1FjLCsnSIr4wrr9qpqsDNjtxQKzvt3CNXgphxcloKvYk/edit#slide=id.p1",
  },
  {
    title: "16_PEOO - POO - 4",
    subtitle: "Herança Múltipla",
    // postedAt: "02/08/2023",
    postedAt: " ",
    link: "https://docs.google.com/presentation/d/12mzEtQibmcZ_LH_wEwkjUQqfNJKDMUx4s0t7EtkngiI/edit#slide=id.p1",
  },
  {
    title: "17_PEOO - POO - Interfaces Gráficas",
    subtitle: "Usando TKInter do Python",
    postedAt: " ",
    link: "https://docs.google.com/presentation/d/1O1AKeb2FHnSntECmkQNKZC_Q_Sir1wVGIOYmBDTMFzU/edit#slide=id.p1",
  },
];

export { slides };
